
import java.awt.Component;
import java.awt.event.KeyEvent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KIIT
 */
public class Home extends javax.swing.JFrame {
private javax.swing.JLabel[] label_name=new javax.swing.JLabel[10]; 
private javax.swing.JButton[] button_add=new javax.swing.JButton[10]; 
private javax.swing.JButton[] button_sub=new javax.swing.JButton[10]; 
private javax.swing.JLabel[] label_count=new javax.swing.JLabel[10]; 
   User_db b=new User_db();
   static String order="";
   Meds_db m=new Meds_db();
   Order_db o=new Order_db();
   
    /**
     * Creates new form Home
     */
   
    static double change(double value)
    {
  
        // Using the pow() method
        value = value * Math.pow(10,2);
        value = Math.floor(value);
        value = value / Math.pow(10,2);
  
        System.out.println(value);
  
        return value;
    }
   
   
   void myinit()
   { int i=0;
       while(i<6)
       {
           label_name[i]=new javax.swing.JLabel();
           label_count[i]=new javax.swing.JLabel();
           button_add[i]=new javax.swing.JButton();
           button_sub[i++]=new javax.swing.JButton();
       }
       label_name[0]=meds1;
      // label_name[0].setLocation(100,380);
       //label_name[0].setText("");
       label_name[1]=meds2;
       label_name[2]=meds3;
       label_name[3]=meds4;
       label_name[4]=meds5;
       label_name[5]=meds6;
       
       label_count[0]=count1;
       label_count[1]=count2;
       label_count[2]=count3;
       label_count[3]=count4;
       label_count[4]=count5;
       label_count[5]=count6;

       button_add[0]=add1;
       button_add[1]=add2;
       button_add[2]=add3;
       button_add[3]=add4;
       button_add[4]=add5;
       button_add[5]=add6;
       
       button_sub[0]=sub1;
       button_sub[1]=sub2;
       button_sub[2]=sub3;
       button_sub[3]=sub4;
       button_sub[4]=sub5;
       button_sub[5]=sub6;
       //getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
   }
    public Home() {
        initComponents();
        myinit();
        
    }
    
    
    
     public Home(User_db b1) {
        b=b1;
        o.u_id=b.u_id;
        o=o.extract_order();
        if(o==null)
            o=new Order_db();
        o.u_id=b.u_id;
        //System.out.println(o.items_count);
        m=m.extract_meds();
         initComponents();
          myinit();
        
    }
    
//    public Home(Order_db o1) {
//        o=o1;
//        System.out.println(o.name[0]+" "+o.name[1]+" "+o.quantity[0]+" "+o.quantity[1]);
//        b.u_id=o.u_id;
//        initComponents();
//        
//    }
    
    public Home(Order_db o1,String id) {
        o=o1;
        o.u_id=id;
        b.u_id=o.u_id;
        m=m.extract_meds();
        initComponents();
         myinit();
        
    }
    
    public Home(User_db b1,Order_db o1) {
        
        b=b1;
        o=o1;
       // o=o.extract_order();
        //if(o==null)
          //  o=new Order_db();
        o.u_id=o1.u_id;
        m=m.extract_meds();
        

        initComponents();
        
     myinit();


        


       
       // j[1]=meds2;
        //System.out.println(j[0].getText());
        
    }
   
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        meds2 = new javax.swing.JLabel();
        add2 = new javax.swing.JButton();
        count2 = new javax.swing.JLabel();
        sub2 = new javax.swing.JButton();
        count1 = new javax.swing.JLabel();
        meds1 = new javax.swing.JLabel();
        sub1 = new javax.swing.JButton();
        add1 = new javax.swing.JButton();
        cartt = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        meds3 = new javax.swing.JLabel();
        meds4 = new javax.swing.JLabel();
        add3 = new javax.swing.JButton();
        sub3 = new javax.swing.JButton();
        count3 = new javax.swing.JLabel();
        add4 = new javax.swing.JButton();
        count4 = new javax.swing.JLabel();
        sub4 = new javax.swing.JButton();
        meds5 = new javax.swing.JLabel();
        add5 = new javax.swing.JButton();
        count5 = new javax.swing.JLabel();
        sub5 = new javax.swing.JButton();
        add6 = new javax.swing.JButton();
        meds6 = new javax.swing.JLabel();
        sub6 = new javax.swing.JButton();
        count6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(300, 20));
        setMinimumSize(new java.awt.Dimension(530, 600));
        setPreferredSize(new java.awt.Dimension(530, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchKeyTyped(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 250, -1));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MEDICINE STORE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 359, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Sign Out");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, 100, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Welcome "+b.u_id+"  ");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 150, -1));

        meds2.setText("Paracetamol");
        getContentPane().add(meds2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 70, -1));

        add2.setText("+");
        add2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add2MouseClicked(evt);
            }
        });
        add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add2ActionPerformed(evt);
            }
        });
        getContentPane().add(add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        count2.setText(""+o.quantity[1]);
        getContentPane().add(count2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, 20));

        sub2.setText("-");
        sub2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sub2MouseClicked(evt);
            }
        });
        sub2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub2ActionPerformed(evt);
            }
        });
        getContentPane().add(sub2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, -1));

        count1.setText(""+o.quantity[0]);
        getContentPane().add(count1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        meds1.setText("Levocetrizine");
        getContentPane().add(meds1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 70, 20));

        sub1.setText("-");
        sub1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sub1MouseClicked(evt);
            }
        });
        sub1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub1ActionPerformed(evt);
            }
        });
        getContentPane().add(sub1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        add1.setText("+");
        add1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add1MouseClicked(evt);
            }
        });
        add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add1ActionPerformed(evt);
            }
        });
        getContentPane().add(add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        cartt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cart1.png"))); // NOI18N
        cartt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cartt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carttMouseClicked(evt);
            }
        });
        getContentPane().add(cartt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 70, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 490, -1));

        meds3.setText("Pantoprazole");
        getContentPane().add(meds3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 70, -1));

        meds4.setText("<html>Oral Dehydration<br>Sachet<html>");
        getContentPane().add(meds4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 130, 40));

        add3.setText("+");
        add3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add3MouseClicked(evt);
            }
        });
        add3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add3ActionPerformed(evt);
            }
        });
        getContentPane().add(add3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        sub3.setText("-");
        sub3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sub3MouseClicked(evt);
            }
        });
        sub3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub3ActionPerformed(evt);
            }
        });
        getContentPane().add(sub3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        count3.setText(""+o.quantity[2]);
        getContentPane().add(count3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        add4.setText("+");
        add4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add4MouseClicked(evt);
            }
        });
        add4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add4ActionPerformed(evt);
            }
        });
        getContentPane().add(add4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));

        count4.setText(""+o.quantity[3]);
        getContentPane().add(count4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, 20));

        sub4.setText("-");
        sub4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sub4MouseClicked(evt);
            }
        });
        sub4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub4ActionPerformed(evt);
            }
        });
        getContentPane().add(sub4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, -1, -1));

        meds5.setText("Telmasartan40");
        getContentPane().add(meds5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 80, 20));

        add5.setText("+");
        add5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add5MouseClicked(evt);
            }
        });
        add5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add5ActionPerformed(evt);
            }
        });
        getContentPane().add(add5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        count5.setText(""+o.quantity[4]);
        getContentPane().add(count5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));

        sub5.setText("-");
        sub5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sub5MouseClicked(evt);
            }
        });
        sub5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub5ActionPerformed(evt);
            }
        });
        getContentPane().add(sub5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, -1, -1));

        add6.setText("+");
        add6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add6MouseClicked(evt);
            }
        });
        add6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add6ActionPerformed(evt);
            }
        });
        getContentPane().add(add6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, -1, -1));

        meds6.setText("Azithromycin");
        getContentPane().add(meds6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 70, 20));

        sub6.setText("-");
        sub6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sub6MouseClicked(evt);
            }
        });
        sub6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub6ActionPerformed(evt);
            }
        });
        getContentPane().add(sub6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, -1, -1));

        count6.setText(""+o.quantity[5]);
        getContentPane().add(count6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, -1, -1));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int e=JOptionPane.showConfirmDialog(null,"Are You Sure?","Select",JOptionPane.YES_NO_OPTION);

        if(e==0)
        {   o.cost=change(o.cost);
            o.insert_order();
        
        new login().setVisible(true); 
        dispose();
       
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    
    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
        // TODO add your handling code here:
        int e=1;
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
               e=JOptionPane.showConfirmDialog(null,"Are You Sure?","Select",JOptionPane.YES_NO_OPTION);
        
        if(e==0)
        {
        setVisible(false);
        new login().setVisible(true); }
        else
            setVisible(true);
    }    
    }//GEN-LAST:event_jButton4KeyPressed

    private void sub2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_sub2ActionPerformed

    private void add2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add2MouseClicked
        // TODO add your handling code here:
        if(o.quantity[1]==4 || o.quantity[1]==m.quantity[1])
            return;
        o.quantity[1]++;
        o.name[1]=m.name[1];
        o.price[1]+=m.price[1];
         o.cost+=m.price[1];
        o.id[1]=m.id[1];
        o.items_count++;
        count2.setText(""+o.quantity[1]);
    }//GEN-LAST:event_add2MouseClicked

    private void sub2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sub2MouseClicked
        // TODO add your handling code here:
        if(o.quantity[1]==0)
            return;
        o.quantity[1]--;
        o.price[1]-=m.price[1];
         o.cost-=m.price[1];
         o.items_count--;
        count2.setText(""+o.quantity[1]);
    }//GEN-LAST:event_sub2MouseClicked

    private void add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add2ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_add2ActionPerformed

    private void carttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carttMouseClicked
        // TODO add your handling code here:
       
        if(o.items_count==0){
            o.insert_order();
            new Cart(b).setVisible(true);
            dispose();
            
        }
        else
        {   
            o.insert_order();
            new Cart(b,o).setVisible(true);
            dispose();
            
        }
    }//GEN-LAST:event_carttMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        
         o.insert_order();
        new Profile(b).setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        // TODO add your handling code here:
         int i=0;
      boolean flag=false;
      int y=0;
      //setLayout(null);
      for(i=0;i<6;i++)
      {   
          label_name[i].setVisible(false);
              label_count[i].setVisible(false);
              button_add[i].setVisible(false);
              button_sub[i].setVisible(false); 
          
          if(label_name[i].getText().toLowerCase().contains(search.getText().toLowerCase()))
          {  
          setLayout(null);
              if(!flag){
              flag=true;
              //label_name[i].setVisible(false);
              label_name[i].setVisible(true);
              label_name[i].setLocation(90,140+y);
               
             // System.out.println(i+" "+label_name[i].getLocation());
             
             label_count[i].setVisible(true);
             
              label_count[i].setLocation(90,180+y); 
              
              button_add[i].setVisible(true);
              button_add[i].setLocation(40,180+y);
              
              button_sub[i].setVisible(true); 
              button_sub[i].setLocation(170,180+y);
              
              
              
          }
                
          else if(flag)
          {  
              
              label_name[i].setVisible(true);
              label_name[i].setLocation(360, 140+y);
              //System.out.println(i+" "+label_name[i].getLocation());
              //getContentPane().add(label_name[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140+y, 70, -1));
              label_count[i].setLocation(370,180+y);
              label_count[i].setVisible(true);
             button_add[i].setLocation(320,180+y);  
              button_add[i].setVisible(true);
              button_sub[i].setLocation(440,180+y);
              button_sub[i].setVisible(true);
              
              
             
              flag=false;
             y+=120; 
          }
          
          }
          
         
      }
      return;
  

    }//GEN-LAST:event_searchKeyReleased

    private void add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add1ActionPerformed

    private void add1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add1MouseClicked
        // TODO add your handling code here:
        if(o.quantity[0]==4 || o.quantity[0]==m.quantity[0])
        return;
        o.quantity[0]++;
        o.name[0]=m.name[0];
        o.price[0]+=m.price[0];
        o.cost+=m.price[0];
        o.id[0]=m.id[0];
        o.items_count++;
        count1.setText(""+o.quantity[0]);

    }//GEN-LAST:event_add1MouseClicked

    private void sub1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub1ActionPerformed

    private void sub1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sub1MouseClicked
        // TODO add your handling code here:
        if(o.quantity[0]==0)
        return;
        o.quantity[0]--;
        o.price[0]-=m.price[0];
        o.cost-=m.price[0];
        o.items_count--;
        count1.setText(""+o.quantity[0]);
    }//GEN-LAST:event_sub1MouseClicked

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_searchKeyPressed

    private void searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_searchKeyTyped

    private void add3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add3MouseClicked
        // TODO add your handling code here:
        if(o.quantity[2]==4 || o.quantity[2]==m.quantity[2])
        return;
        o.quantity[2]++;
        o.name[2]=m.name[2];
        o.price[2]+=m.price[2];
        o.cost+=m.price[2];
        o.id[2]=m.id[2];
        o.items_count++;
        count3.setText(""+o.quantity[2]);
    }//GEN-LAST:event_add3MouseClicked

    private void add3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add3ActionPerformed

    private void sub3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sub3MouseClicked
        // TODO add your handling code here:
        if(o.quantity[2]==0)
        return;
        o.quantity[2]--;
        o.price[2]-=m.price[2];
        o.cost-=m.price[2];
        o.items_count--;
        count3.setText(""+o.quantity[2]);
    }//GEN-LAST:event_sub3MouseClicked

    private void sub3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub3ActionPerformed

    private void add4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add4MouseClicked
        // TODO add your handling code here:
         if(o.quantity[3]==4 || o.quantity[3]==m.quantity[3])
        return;
        o.quantity[3]++;
        o.name[3]=m.name[3];
        o.price[3]+=m.price[3];
        o.cost+=m.price[3];
        o.id[3]=m.id[3];
        o.items_count++;
        count4.setText(""+o.quantity[3]);
       
    }//GEN-LAST:event_add4MouseClicked

    private void add4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add4ActionPerformed

    private void sub4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sub4MouseClicked
        // TODO add your handling code here:
        if(o.quantity[3]==0)
        return;
        o.quantity[3]--;
        o.price[3]-=m.price[3];
        o.cost-=m.price[3];
        o.items_count--;
        count4.setText(""+o.quantity[3]);
    }//GEN-LAST:event_sub4MouseClicked

    private void sub4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub4ActionPerformed

    private void add5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add5MouseClicked
        // TODO add your handling code here:
         if(o.quantity[4]==4 || o.quantity[4]==m.quantity[4])
        return;
        o.quantity[4]++;
        o.name[4]=m.name[4];
        o.price[4]+=m.price[4];
        o.cost+=m.price[4];
        o.id[4]=m.id[4];
        o.items_count++;
        count5.setText(""+o.quantity[4]);
    }//GEN-LAST:event_add5MouseClicked

    private void add5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add5ActionPerformed

    private void sub5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sub5MouseClicked
        // TODO add your handling code here:
        if(o.quantity[4]==0)
        return;
        o.quantity[4]--;
        o.price[4]-=m.price[4];
        o.cost-=m.price[4];
        o.items_count--;
        count5.setText(""+o.quantity[4]);
    }//GEN-LAST:event_sub5MouseClicked

    private void sub5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub5ActionPerformed

    private void add6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_add6MouseClicked

    private void add6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add6ActionPerformed
        // TODO add your handling code here:
         if(o.quantity[5]==4 || o.quantity[5]==m.quantity[5])
        return;
        o.quantity[5]++;
        o.name[5]=m.name[5];
        o.price[5]+=m.price[5];
        o.cost+=m.price[5];
        o.id[5]=m.id[5];
        o.items_count++;
        count6.setText(""+o.quantity[5]);
    }//GEN-LAST:event_add6ActionPerformed

    private void sub6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sub6MouseClicked
        // TODO add your handling code here:
        if(o.quantity[5]==0)
        return;
        o.quantity[5]--;
        o.price[5]-=m.price[5];
        o.cost-=m.price[5];
        o.items_count--;
        count6.setText(""+o.quantity[5]);
    }//GEN-LAST:event_sub6MouseClicked

    private void sub6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub6ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add1;
    private javax.swing.JButton add2;
    private javax.swing.JButton add3;
    private javax.swing.JButton add4;
    private javax.swing.JButton add5;
    private javax.swing.JButton add6;
    private javax.swing.JLabel cartt;
    private javax.swing.JLabel count1;
    private javax.swing.JLabel count2;
    private javax.swing.JLabel count3;
    private javax.swing.JLabel count4;
    private javax.swing.JLabel count5;
    private javax.swing.JLabel count6;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel meds1;
    private javax.swing.JLabel meds2;
    private javax.swing.JLabel meds3;
    private javax.swing.JLabel meds4;
    private javax.swing.JLabel meds5;
    private javax.swing.JLabel meds6;
    private javax.swing.JTextField search;
    private javax.swing.JButton sub1;
    private javax.swing.JButton sub2;
    private javax.swing.JButton sub3;
    private javax.swing.JButton sub4;
    private javax.swing.JButton sub5;
    private javax.swing.JButton sub6;
    // End of variables declaration//GEN-END:variables
}
