/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KIIT
 */
public class Order_history extends javax.swing.JFrame {
  String u_id;
  String[] oid=new String[10];
  double[] cost=new double[10];
  String[] date=new String[10];
    /**
     * Creates new form Order_history
     */
    public Order_history() {
        initComponents();
    }
    
    public Order_history(String id) {
        u_id=id;
        
        Order_history oh1=new Order_history();
        initComponents();
        oh1=funs.extract_history(this,u_id);
        if(oh1==null)
        {System.out.println("HII");
            display_area.setText("\t\tNo Orders Available !!!");
            oh1=new Order_history();
            search.setVisible(false);
            search_button.setVisible(false);
            track.setVisible(false);
            return ;
        }
        else    
        history(oh1);
        
        
        
        
    }

    void history(Order_history oh1)
    {
        int i=0;
        //boolean flag=false;
        display_area.setText("Order ID\t\t"+"Cost\t\t"+"Date\n\n");
        while(i<6)
        {
            if(oh1.oid[i]!=null)
//                flag=true;
                display_area.append(oh1.oid[i]+"\t\t"+Home.change(oh1.cost[i])+"\t\t"+oh1.date[i]+"\n");
            //}
            i++;
        }
            
//        if(flag==false)
//            jTextArea1.setText("\t\tNo Orders Available !!!");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        display_area = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        search = new javax.swing.JTextField();
        search_button = new javax.swing.JButton();
        track = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(530, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        display_area.setEditable(false);
        display_area.setEditable(false);
        display_area.setColumns(3);
        display_area.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        display_area.setRows(6);
        display_area.setOpaque(false);
        display_area.setBackground(new java.awt.Color(0,0,0,0));
        jScrollPane1.setViewportView(display_area);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setOpaque(false);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 500, 170));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 410, -1));

        search.setForeground(new java.awt.Color(204, 204, 204));
        search.setText("Search Order");
        search.setCaretPosition(0);
        search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchFocusLost(evt);
            }
        });
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchMousePressed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 180, -1));

        search_button.setText("Search");
        search_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_buttonMouseClicked(evt);
            }
        });
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(search_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        track.setText("Track Order");
        track.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trackMouseClicked(evt);
            }
        });
        getContentPane().add(track, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        // TODO add your handling code here:
//        if(search.getText().equals("Search Order")){
//        search.setCaretPosition(0);
//            search.setText("");
//        //search.setEditable(true);
//        
//        search.setForeground(new java.awt.Color(0, 0, 0));
//        }
        
    }//GEN-LAST:event_searchMouseClicked

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_buttonActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        // TODO add your handling code here:
        if(search.getText().equals("")){
            search.setText("Search Order");
            //search.setEditable(false);
            search.setCaretPosition(0);
            search.setForeground(new java.awt.Color(204, 204, 204));
            history(this);
            return;}
        
            
    }//GEN-LAST:event_searchKeyReleased

    private void search_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_buttonMouseClicked
        // TODO add your handling code here:
        Order_db o1=new Order_db();
        o1.u_id=u_id;
        String oid=search.getText();
        if(funs.extract_placed_order(o1,oid)==null)
        {
            display_area.setText("Order ID : "+oid+" doesn't exists !!!");
            return ;
        }
        
        display_area.setText("Order ID : "+oid);
        display_area.append("\n\nItem\t\tQuantity\t\tPrice\n\n");
        
        int i=0;
        while(i<6)
        {   if(o1.quantity[i]==0)
        {
            i++;
            continue;
        }
         if(o1.name[i].length()>13) 
        display_area.append(o1.name[i].substring(0, Math.min(o1.name[i].length(), 10)).concat("...")+"\t\t"+o1.quantity[i]+"\t\t"+o1.price[i]+"\n");
         else   
         display_area.append(o1.name[i]+"\t\t"+o1.quantity[i]+"\t\t"+o1.price[i]+"\n");
            i++;
        }
               
    }//GEN-LAST:event_search_buttonMouseClicked

    private void searchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFocusLost
        // TODO add your handling code here:
      
    }//GEN-LAST:event_searchFocusLost

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        // TODO add your handling code here:
        if(search.getText().equals("Search Order")){
        search.setText("");
       // search.setEditable(true);
        search.setCaretPosition(0);
        search.setForeground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_searchKeyPressed

    private void searchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMousePressed
        // TODO add your handling code here:
          if(search.getText().equals("Search Order")){
        search.setText("");
       // search.setEditable(true);
        search.setCaretPosition(0);
        search.setForeground(new java.awt.Color(0, 0, 0));
          }
    }//GEN-LAST:event_searchMousePressed
   
    private void searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseExited
        // TODO add your handling code here:
        if(search.getText().equals("")){
        search.setText("Search Order");
       // search.setEditable(true);
        search.setCaretPosition(0);
        search.setForeground(new java.awt.Color(204, 204, 204));
          }
    }//GEN-LAST:event_searchMouseExited

    private void trackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trackMouseClicked
        // TODO add your handling code here:
        new track_order(u_id).setVisible(true);
    }//GEN-LAST:event_trackMouseClicked
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order_history().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea display_area;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField search;
    private javax.swing.JButton search_button;
    private javax.swing.JButton track;
    // End of variables declaration//GEN-END:variables
}
