
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KIIT
 */
public class Order_summary extends javax.swing.JFrame {
User_db b=new User_db();
Order_db o=new Order_db();
boolean select=false;
    /**
     * Creates new form Order_summary
     */
    public Order_summary() {
        initComponents();
    }
    
    public Order_summary(User_db b1,Order_db o1) {
        b=b1;
        o=o1;
        System.out.println(b.address);
        initComponents();
        var group = new ButtonGroup();
           group.add(online);
      group.add(upi);
      group.add(cod);
      
        display_order();
    }

    
    void display_order()
    {
         int i=0;
       double total=0.0;
        while(i<6){
         if(o.quantity[i]!=0){  
          if(o.name[i].length()>13) 
        jTextArea1.append(o.name[i].substring(0, Math.min(o.name[i].length(), 10)).concat("...")+"\t\t\t"+o.quantity[i]+"\t\t"+o.price[i]+"\n");
        
         
          else
              jTextArea1.append(o.name[i]+"\t\t\t"+o.quantity[i]+"\t\t"+o.price[i]+"\n");
            
          total+=o.price[i];
        
        }
         i++;
        
    }
        total=Home.change(total);
         total_price.setText("Total Price : "+total); 
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        total_price = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        online = new javax.swing.JRadioButton();
        upi = new javax.swing.JRadioButton();
        cod = new javax.swing.JRadioButton();
        place_order = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        add = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ph = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(531, 736));
        setPreferredSize(new java.awt.Dimension(531, 736));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Order Summary");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jTextArea1.setText("Item\t\t\t"+"Quantity\t\t"+"Price\n\n");
        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setOpaque(false);
        jTextArea1.setBackground(new java.awt.Color(0,0,0,0));
        jScrollPane1.setViewportView(jTextArea1);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setOpaque(false);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 500, 130));

        total_price.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        total_price.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(total_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 150, 30));

        jLabel5.setText("Payment Method");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        online.setText("Net Banking/ Debit/ Credit Card");
        online.setOpaque(false);
        online.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onlineMouseClicked(evt);
            }
        });
        getContentPane().add(online, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        upi.setText("UPI");
        upi.setOpaque(false);
        upi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upiMouseClicked(evt);
            }
        });
        getContentPane().add(upi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 190, -1));

        cod.setText("Cash On Delivery (COD)");
        cod.setOpaque(false);
        cod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                codMouseClicked(evt);
            }
        });
        getContentPane().add(cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        place_order.setText("Place Order");
        place_order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                place_orderMouseClicked(evt);
            }
        });
        getContentPane().add(place_order, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, -1, -1));

        close.setText("Close");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, 80, -1));

        jLabel3.setText("Enter Address");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        add.setText(b.address);
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 290, 40));

        jLabel4.setText("Enter Phone No.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        ph.setText(b.phone);
        getContentPane().add(ph, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 160, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        new Cart(b,o).setVisible(true);
        dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void place_orderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_place_orderMouseClicked
        // TODO add your handling code here:
        if(select==false)
        {
            JOptionPane.showMessageDialog(null,"Choose One Payment Option...");
            return;
        }
        o.items_count=0;
        funs.insert_placed_order(o);
        funs.insert_track_order(o.u_id,o.oid);
        o.insert_order();
        o.add_order();
        
        new Home(b).setVisible(true);
        dispose();        
    }//GEN-LAST:event_place_orderMouseClicked

    private void onlineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onlineMouseClicked
        // TODO add your handling code here:
        select=true;
    }//GEN-LAST:event_onlineMouseClicked

    private void upiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upiMouseClicked
        // TODO add your handling code here:
        select=true;
    }//GEN-LAST:event_upiMouseClicked

    private void codMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codMouseClicked
        // TODO add your handling code here:
        select=true;
    }//GEN-LAST:event_codMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order_summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order_summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order_summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order_summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order_summary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private javax.swing.JButton close;
    private javax.swing.JRadioButton cod;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton online;
    private javax.swing.JTextField ph;
    private javax.swing.JButton place_order;
    private javax.swing.JLabel total_price;
    private javax.swing.JRadioButton upi;
    // End of variables declaration//GEN-END:variables
}
