/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KIIT
 */
public class track_order extends javax.swing.JFrame {
String u_id;
String[] oid=new String[10];
String[] date=new String[10];
String[] status=new String[10];

    /**
     * Creates new form track_order
     */
    public track_order() {
        initComponents();
    }
    
    public track_order(String id) {
        u_id=id;
        track_order to1;
        to1=funs.extract_track_order(this);
        initComponents();
        if(to1==null)
        {
            search.setVisible(false);
            search_button.setVisible(false);
            display_area.setText("\t\tNo Orders available !!!");
            return;
        }
        else
            display_order();
        
    }
    
    void display_order()
    {
        int i=0;
        display_area.setText("Order ID\t\tStatus\t\tExpected Delivery\n\n");
        while(i<6)
        {
            if(oid[i]==null)
                return;
            display_area.append(oid[i]+"\t\t"+status[i]+"\t\t"+date[i]+"\n");
            i++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        search = new javax.swing.JTextField();
        search_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        display_area = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(530, 300));
        setPreferredSize(new java.awt.Dimension(530, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.setForeground(new java.awt.Color(204, 204, 204));
        search.setText("Search Order");
        search.setCaretPosition(0);
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchMousePressed(evt);
            }
        });
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 20, 150, -1));

        search_button.setText("Search");
        search_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_buttonMouseClicked(evt);
            }
        });
        getContentPane().add(search_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        display_area.setColumns(20);
        display_area.setRows(5);
        jScrollPane1.setViewportView(display_area);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 510, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void searchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMousePressed
        // TODO add your handling code here:
         if(search.getText().equals("Search Order")){
        search.setText("");
       // search.setEditable(true);
        search.setCaretPosition(0);
        search.setForeground(new java.awt.Color(0, 0, 0));
          }
    }//GEN-LAST:event_searchMousePressed

    private void searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseExited
        // TODO add your handling code here:
         if(search.getText().equals("")){
        search.setText("Search Order");
       // search.setEditable(true);
        search.setCaretPosition(0);
        search.setForeground(new java.awt.Color(204, 204, 204));
          }
    }//GEN-LAST:event_searchMouseExited

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        // TODO add your handling code here:
       if(search.getText().equals("")){
            search.setText("Search Order");
            //search.setEditable(false);
            search.setCaretPosition(0);
            search.setForeground(new java.awt.Color(204, 204, 204));
            display_order();
            return;}
    }//GEN-LAST:event_searchKeyReleased

    private void search_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_buttonMouseClicked
        // TODO add your handling code here:
         
        String o_id=search.getText();
       int i=0;
       
       while(i<6)
       {
           if(o_id.equals(oid[i]))
           {
            display_area.setText("Order ID\t\tStatus\t\tExpected Delivery\n\n");
            display_area.append(oid[i]+"\t\t"+status[i]+"\t\t"+date[i]+"\n");
            return ;
           }
           
           
           i++;
       }
         display_area.setText("Order ID : "+o_id+"doesn't exists !!!"); 
    }//GEN-LAST:event_search_buttonMouseClicked

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        // TODO add your handling code here:
         if(search.getText().equals("Search Order")){
        search.setText("");
       // search.setEditable(true);
        search.setCaretPosition(0);
        search.setForeground(new java.awt.Color(0, 0, 0));
        }
    }//GEN-LAST:event_searchKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(track_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(track_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(track_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(track_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new track_order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea display_area;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField search;
    private javax.swing.JButton search_button;
    // End of variables declaration//GEN-END:variables
}
